# Generated by Django 4.2.3 on 2023-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comida', models.CharField(max_length=1000)),
                ('Hoteles', models.CharField(max_length=1000)),
                ('Transporte', models.CharField(max_length=1000)),
                ('Tips_generales', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destino', models.CharField(max_length=100)),
                ('Atraccion_principal', models.CharField(max_length=1000)),
            ],
        ),
    ]
