# Generated by Django 4.2.3 on 2023-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0002_contactos_paginas_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejos',
            name='Destino',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
