# Generated by Django 4.2.3 on 2023-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0003_consejos_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='Descripcion',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
