# Generated by Django 4.2.3 on 2023-09-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0004_destinos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginas_web',
            name='Link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
