# Generated by Django 4.2.3 on 2023-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0005_paginas_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destino_images/'),
        ),
    ]
