# Generated by Django 4.2.3 on 2023-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0009_remove_thread_mensaje_remove_thread_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas_web',
            name='Link',
            field=models.URLField(),
        ),
    ]
